// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Semente.Models;
using System;

namespace Semente.Migrations
{
    [DbContext(typeof(SementeContext))]
    [Migration("20170928111515_Farmaco")]
    partial class Farmaco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Semente.Models.Farmaco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Farmaco");
                });

            modelBuilder.Entity("Semente.Models.Medicamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FarmacoId");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.HasIndex("FarmacoId");

                    b.ToTable("Medicamento");
                });

            modelBuilder.Entity("Semente.Models.Medicamento", b =>
                {
                    b.HasOne("Semente.Models.Farmaco", "Farmaco")
                        .WithMany()
                        .HasForeignKey("FarmacoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
